# Generated by Django 3.2.25 on 2024-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2005-01-01', verbose_name='Дата рождения'),
        ),
    ]
