# Generated by Django 3.2.25 on 2024-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите категорию', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категорию', to='applications.Category'),
        ),
    ]
