# Generated by Django 3.2.25 on 2024-11-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20241108_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.category'),
        ),
    ]
