# Generated by Django 5.1.3 on 2024-11-08 13:55

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20241108_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='applications/', validators=[applications.models.validate_image]),
        ),
    ]
