# Generated by Django 3.2.25 on 2024-11-09 05:54

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20241109_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/', validators=[applications.models.validate_image]),
        ),
    ]
